# -*- coding: utf-8 -*-
"""Imagevision_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1elDjrTi_Gih6Qx7Ng2WTgYPd1kovrW7s
"""

!pip install pytesseract
!apt-get install tesseract-ocr
!pip install transformers
!pip install torch torchvision

from google.colab import drive
drive.mount('/content/drive')

import os

# Path to  dataset directory
image_directory = '/content/drive/MyDrive/invoices_dataset_final/images'
annotation_directory = '/content/drive/MyDrive/invoices_dataset_final/Annotations'

# List image files
image_files = os.listdir(image_directory)
print("Image files:", image_files)

# List annotation files
annotation_files = os.listdir(annotation_directory)
print("Annotation files:", annotation_files)

from PIL import Image

# Load and display an example image
if image_files:
    example_image_file = image_files[0]  # Load the first image
    image_path = os.path.join(image_directory, example_image_file)
    image = Image.open(image_path)
    image.show()
else:
    print("No images found in the directory.")

import pytesseract

# Extract text using Tesseract
extracted_text = pytesseract.image_to_string(image)
print("Extracted Text:\n", extracted_text)